title: Brendan Tan # your name (or website title) here
logo: "/images/cropped1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I'm Brendan, and I'm on a mission to become a proficient data scientist, 
  driven by a passion for leveraging data to drive insights and innovation. 
  <br><br>
  My journey into the world of data science began in April 2022 when 
  I stumbled upon an online bootcamp. There, I discovered the power of crafting code to create insightful dashboards 
  for business intelligence and building robust machine learning models. 
  This revelation sparked a deep curiosity that propelled me into the field. 
  <br><br>
  Eager to equip myself with the essential skills, 
  I enrolled in a 6 month part-time data science bootcamp at General Assembly. 
  Through this intensive experience, I gained hands-on experience with tools like Python, 
  SQL, and machine learning algorithms, laying the foundation for my career in data science.
  <br><br>
  In today's fast-paced tech landscape, I recognize the importance of continuous learning and adaptation. 
  I stay abreast of the latest trends and advancements in data science, 
  constantly seeking opportunities to upskill and apply 
  innovative solutions to real-world challenges.
  <br><br>
  I've had the opportunity to work on projects ranging from predictive analytics 
  to natural language processing, each offering valuable lessons and insights. 
  I'm excited to continue exploring the endless possibilities that data science offers 
  and to contribute meaningfully to the field.
  <br><br>
  Feel free to explore the projects and insights I've shared, 
  and I look forward to connecting with you!
  <br><br>
  <a href="https://www.linkedin.com/in/brendan-tan/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
